# 수업에 사용될 라이브러리 설치

In [1]:
dir  # 윈도우 사용자의 경우 -> dir 

<function dir>

In [2]:
pip install numpy


[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
!pip install -r requirements.txt

  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [1929 lines of output]
  C:\Users\user\AppData\Local\Temp\pip-install-eoiahwbx\pandas_dea41e6660974f5d8e990023d64ac9c6\setup.py:54: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\pandas
  copying pandas\conftest.py -> build\lib.win-amd64-3.9\pandas
  copying pandas\testing.py -> build\lib.win-amd64-3.9\pandas
  copying pandas\_typing.py -> build\lib.win-amd64-3.9\pandas
  copying pandas\_version.py -> build\lib.win-amd64-3.9\pandas
  copying pandas\__init__.py -> build\lib.win-amd64-3.9\pandas
  creating build\lib.win-amd64-3.9\pandas\api
  copying pandas\api\__init__.py -> build\lib.win-amd64-3.9\pandas\api
  creating build\


  Using cached pandas-0.25.3.tar.gz (12.6 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): still running...
  Preparing metadata (setup.py): finished with status 'done'
  Using cached numpy-1.17.0.zip (6.5 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached seaborn-0.9.0-py3-none-any.whl (208 kB)
  Using cached matplotlib-3.1.1.tar.gz (37.8 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached finance_datareader-0.9.1-py3-none-any.whl (17 kB)
  Running setup.py clean for pandas
  Running setup.py clean for numpy
  Running setup.py clean for matplotlib
Failed to build pandas numpy matplotlib
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.5
    Uninstalling numpy-1.21.5:
      Successfully uninstalled numpy-1.21.5
  Running setup.py install for numpy: started
  Running setup.py install for numpy: f


  copying pandas\core\computation\engines.py -> build\lib.win-amd64-3.9\pandas\core\computation
  copying pandas\core\computation\eval.py -> build\lib.win-amd64-3.9\pandas\core\computation
  copying pandas\core\computation\expr.py -> build\lib.win-amd64-3.9\pandas\core\computation
  copying pandas\core\computation\expressions.py -> build\lib.win-amd64-3.9\pandas\core\computation
  copying pandas\core\computation\ops.py -> build\lib.win-amd64-3.9\pandas\core\computation
  copying pandas\core\computation\pytables.py -> build\lib.win-amd64-3.9\pandas\core\computation
  copying pandas\core\computation\scope.py -> build\lib.win-amd64-3.9\pandas\core\computation
  copying pandas\core\computation\__init__.py -> build\lib.win-amd64-3.9\pandas\core\computation
  creating build\lib.win-amd64-3.9\pandas\core\dtypes
  copying pandas\core\dtypes\api.py -> build\lib.win-amd64-3.9\pandas\core\dtypes
  copying pandas\core\dtypes\base.py -> build\lib.win-amd64-3.9\pandas\core\dtypes
  copying pandas\c

  copying pandas\tests\tslibs\test_timedeltas.py -> build\lib.win-amd64-3.9\pandas\tests\tslibs
  copying pandas\tests\tslibs\test_timezones.py -> build\lib.win-amd64-3.9\pandas\tests\tslibs
  copying pandas\tests\tslibs\__init__.py -> build\lib.win-amd64-3.9\pandas\tests\tslibs
  creating build\lib.win-amd64-3.9\pandas\tests\util
  copying pandas\tests\util\conftest.py -> build\lib.win-amd64-3.9\pandas\tests\util
  copying pandas\tests\util\test_assert_almost_equal.py -> build\lib.win-amd64-3.9\pandas\tests\util
  copying pandas\tests\util\test_assert_categorical_equal.py -> build\lib.win-amd64-3.9\pandas\tests\util
  copying pandas\tests\util\test_assert_extension_array_equal.py -> build\lib.win-amd64-3.9\pandas\tests\util
  copying pandas\tests\util\test_assert_frame_equal.py -> build\lib.win-amd64-3.9\pandas\tests\util
  copying pandas\tests\util\test_assert_index_equal.py -> build\lib.win-amd64-3.9\pandas\tests\util
  copying pandas\tests\util\test_assert_interval_array_equal.py -

  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\user\anaconda3\libs /LIBPATH:C:\Users\user\anaconda3 /LIBPATH:C:\Users\user\anaconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\lib\x64" "/LIBPATH:E:\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:E:\Windows Kits\10\lib\10.0.18362.0\um\x64" /EXPORT:PyInit_tslib build\temp.win-amd64-3.9\Release\pandas/_libs/tslibs/src/datetime/np_datetime.obj build\temp.win-amd64-3.9\Release\pandas/_libs/tslibs/src/datetime/np_datetime_strings.obj build\temp.win-amd64-3.9\Release\pandas\_libs/tslib.obj /OUT:build\lib.win-amd64-3.9\pandas\_libs\tslib.cp39-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.9\Release\panda

  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Inumpy\core\src\common -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\Users\user\anaconda3\include -IC:\Users\user\anaconda3\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include -IE:\Windows Kits\10\include\10.0.18362.0\ucrt -IE:\Windows Kits\10\include\10.0.18362.0\shared -IE:\Windows Kits\10\include\10.0.18362.0\um -IE:\Windows Kits\10\include\10.0.18362.0\winrt -IE:\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tc_configtest.c /Fo_configtest.obj
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MAN

  copying lib\matplotlib\mpl-data\fonts\afm\cmr10.afm -> build\lib.win-amd64-3.9\matplotlib\mpl-data\fonts\afm
  copying lib\matplotlib\mpl-data\images\hand.svg -> build\lib.win-amd64-3.9\matplotlib\mpl-data\images
  copying lib\matplotlib\mpl-data\images\move.png -> build\lib.win-amd64-3.9\matplotlib\mpl-data\images
  copying lib\matplotlib\mpl-data\sample_data\s1045.ima.gz -> build\lib.win-amd64-3.9\matplotlib\mpl-data\sample_data
  copying lib\matplotlib\mpl-data\images\zoom_to_rect.gif -> build\lib.win-amd64-3.9\matplotlib\mpl-data\images
  copying lib\matplotlib\mpl-data\fonts\afm\pncb8a.afm -> build\lib.win-amd64-3.9\matplotlib\mpl-data\fonts\afm
  copying lib\matplotlib\mpl-data\fonts\afm\phvr8a.afm -> build\lib.win-amd64-3.9\matplotlib\mpl-data\fonts\afm
  copying lib\matplotlib\mpl-data\images\move.svg -> build\lib.win-amd64-3.9\matplotlib\mpl-data\images
  copying lib\matplotlib\mpl-data\fonts\afm\pagdo8a.afm -> build\lib.win-amd64-3.9\matplotlib\mpl-data\fonts\afm
  copying 

# Numpy 소개

In [4]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [5]:
import numpy as np

## ndarray dtype

병렬연산 가능한 리스트

In [6]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [8]:
# indexing이 list와 방식이 같음
a[0]

1

In [9]:
a.

SyntaxError: invalid syntax (3905452595.py, line 1)

- append() 같은 함수가 없음 -> 즉, python의 list와는 다른 data type임

## Universal function

In [10]:
a = [1, 2, 3]
b = [4, 5, 6]

new_list = []
for e1, e2 in zip(a, b):
    new_list.append(e1 + e2)
new_list

[5, 7, 9]

In [11]:
a + b

[1, 2, 3, 4, 5, 6]

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [13]:
# 길이가 길어도 근사적으로 1초가 걸린다
# 벡터화해서 연산속도 높인다
a + b

array([5, 7, 9])

In [14]:
# np.sum
# np.abs
# np.log
# np.exp
# np.isnan
# ...

- n차원 array

In [15]:
a = np.array([  [1, 2],  [3, 4]   ])
a

array([[1, 2],
       [3, 4]])

In [16]:
# readability 높이기
a = np.array(
    [
        [1, 2],
        [3, 4],
    ]
)

In [17]:
a[0][1]

2

In [18]:
a + a

array([[2, 4],
       [6, 8]])